### ISSUE TITLE
Generic Types

### ISSUE THREAD

**Issue by FreeCX** [pinecrew/linal#3]
Rewrite code to generic types.

To write code with generic types we need use `Zero` trait, but it unstable for now.

**Comment by FreeCX** [comment]
To write code with generic types we need use `Zero` trait, but it unstable for now.

**Comment by citrux** [comment]
We can write own `Zero` trait for solve this problem, while standard trait is unstable.

**Comment by citrux** [comment]
I close it, and if we will need it in future, just reopen this issue.
