### ISSUE TITLE
Cross product trait

### ISSUE THREAD

**Issue by citrux** [pinecrew/linal#6]
I add `Cross` trait for same syntax in two different cases:

``` rust
let a = Vec2::new(...);
let b = Vec2::new(...);
let c = 1f64; // orthogonal to plane vector with length 1
a.cross(b); // return f64
a.cross(c); // return Vec2
```

But explicit import of trait is bad. And we can remove trait with new approach to `cross` in 2d:

``` rust
impl Vec2 {
...
pub fn cross(self) -> Vec2 {
    return Vec2::new(self.y, -self.x)
}
...
}
...
let a = Vec2::new(...);
let b = Vec2::new(...);
let c = 1f64; // orthogonal to plane vector with length 1
a.dot(b.cross()); // or b.cross().dot(a) is an old a.cross(b)
a.cross()*c; // a.cross(c)
```

**Comment by FreeCX** [comment]
@citrux, how convenient will use this code

``` rust
a.dot(b.cross()); // or b.cross().dot(a) is an old a.cross(b)
a.cross()*c; // a.cross(c)
```

May be to use two different functions?

**Comment by citrux** [comment]
Some math background needed: cross product in 3d for 2 vectors returns 3, orthogonal to both. In 2d we can construct orthogonal vector to one, not two vectors. And this vector I understand as cross product (of one vector, it doesn't binary operation) in 2d. Mathematically it looks like this:
![](http://latex2png.com/output//latex_e2a07914bea21f9f2229ffd24f6c119a.png)
![](http://latex2png.com/output//latex_e8ec555637cb5d505e0e4bb95c8a3d0d.png)
