### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by citrux** [pinecrew/linal#7]
Add changelog to readme or in special file (markdown?)

**Comment by FreeCX** [comment]
@citrux, i think need to create `Changelog` or `Changes` file (with markdown).

**Comment by citrux** [comment]
Maybe `CHANGELOG.md` like other text files names?

**Comment by FreeCX** [comment]
Ok.

**Comment by citrux** [comment]
@FreeCX, append to changelog items I forgot. I think, we can add links to code.

**Comment by FreeCX** [comment]
@citrux, i will write everything that remember.
Later.
